services:
  - type: web
    name: file-uploader
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: file-uploader-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: APP_BASE_URL
        value: https://file-uploader.onrender.com

databases:
  - name: file-uploader-db
    databaseName: fileuploader
    user: fileuser
